//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace CSharpLua {
  public sealed partial class XmlMetaProvider {

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class doc {

      private object[] itemsField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("assembly", typeof(docAssembly), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      [System.Xml.Serialization.XmlElementAttribute("members", typeof(docMembers), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public object[] Items {
        get {
          return this.itemsField;
        }
        set {
          this.itemsField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class docAssembly {

      private string nameField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string name {
        get {
          return this.nameField;
        }
        set {
          this.nameField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class docMembers {

      private docMembersMember[] memberField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("member", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public docMembersMember[] member {
        get {
          return this.memberField;
        }
        set {
          this.memberField = value;
        }
      }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class docMembersMember {

      // private string summaryField;

      private string nameField;

      /// <remarks/>
      /*[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string summary {
        get {
          return this.summaryField;
        }
        set {
          this.summaryField = value;
        }
      }*/

      [System.Xml.Serialization.XmlText()]
      public System.Xml.XmlNode[] node { get; set; }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string name {
        get {
          return this.nameField;
        }
        set {
          this.nameField = value;
        }
      }
    }
  }
}
